name: Test
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4'
          otp-version: '27.3'
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: mix deps.get --check-locked
      - run: mix test
